apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ${CI_PROJECT_PATH_SLUG}-data-updates
spec:
  schedule: "0 0 20 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ${CI_PROJECT_PATH_SLUG}-data-updates
              image: ${CI_REGISTRY_IMAGE}/fpm:${CI_ENVIRONMENT_SLUG}
              imagePullPolicy: Always
              command: ['/bin/sh']
              args:
                - -c
                - >
                  apk add php7 &&
                  cd /srv/http/nox &&
                  env UPDATE_MONTH_FROM=auto php artisan db:seed --force --class=MonthlyValueSeeder
              volumeMounts:
                - name: configs
                  mountPath: /srv/http/nox/.env
                  subPath: .env
          volumes:
            - name: configs
              configMap:
                name: ${CI_PROJECT_PATH_SLUG}-configs
          restartPolicy: OnFailure
