FROM alpine:latest
RUN apk add php7-fpm php7-dom php7-fileinfo php7-json php7-xml php7-mbstring php7-openssl php7-tokenizer php7-pdo_mysql
ADD app.tar /srv/http/nox
RUN chown -R nobody:nobody /srv/http/nox/storage
CMD php-fpm7
