FROM alpine:latest
RUN apk add nginx
RUN echo 'daemon off;' >> /etc/nginx/nginx.conf
RUN mkdir /run/nginx
ADD app.tar /srv/http/nox
ADD containers/nginx-server.conf /etc/nginx/conf.d/default.conf
CMD nginx -c /etc/nginx/nginx.conf
