{
 "title": "nox",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Ambient temperature -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  amb_temp,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "SO₂ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  so2,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "CO -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  co,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "CO₂ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  co2,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "O₃ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  o3,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "PM₁₀ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  pm10,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "PM₂.₅ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "conμgm3" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  pm25,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "NOₓ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  nox,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "NO -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  no,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "NO₂ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "conppb" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  no2,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "THC -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  thc,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "NMHC -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  nmhc,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "CH₄ -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  ch4,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "Wind speed -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  wind_speed,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "WS_HR -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  ws_hr,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "RAIN_INT -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  rain_int,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "PH_RAIN -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none", "label": "pH" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  ph_rain,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "RH -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  rh,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  },
  {
   "title": "RAIN_COND -- monthly value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "μS/cm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(month) AS \"time\",\n  rain_cond,\n  stations.name as metric\nFROM monthly_values INNER JOIN stations ON monthly_values.station_id = stations.id\nWHERE UNIX_TIMESTAMP(month) BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nORDER BY UNIX_TIMESTAMP(month)"
    }
   ]
  }
 ]
}